# Is it possible to have hierarchical config files? XML? Hydra?
#################### DATA LOCATION ####################
'data_file': [{"train_file": 'data/460-464-466_201710_30_train_0.csv', "test_file": 'data/460-464-466_201710_30_test_0.csv'},
              {"train_file": 'data/460-464-466_201710_30_train_1.csv', "test_file": 'data/460-464-466_201710_30_test_1.csv'}]
#################### MODEL LOCATION ####################
'model_type': ["RCNN"]
'model_name': ["RCNN-resnet-50"]
'base_model_path': ["models/templates/RCNN-resnet-50_5_layer_pretrained_basic_backbone.pt"]
'output_dir': ["models/trained"]
#################### TASK ####################
'task_name': ["seedlings_extra_data_vanilla_2"]
'task_description': ["We've been seeing plateuing behaviour but have never really seen an overfit on the data.
                     Perhaps after a plateu there will be further improvements?"]
# Could include optimizer hyperparams by making this nested. Maybe different config files for optimiser here?
#################### TRAINING ####################
'optimiser': ['SGD']
'learning_rate': [2.0e-3]
'momentum': [0.9]
'weight_decay': [1.0e-4]
'epochs': [300]
'patience': [300]
'valid_ratio': [0.1]
'dataloader_num_workers': [5]
'train_batch_size': [5]
'eval_batch_size': [5]
'max_seq_length': [512]
'logging_steps': [2]
'seed': [1337]
'num_weights_tracked': [10]
'device': ["cuda:0"]
'develop': [False]
'clip': [1]