# Is it possible to have hierarchical config files? XML? Hydra?
#################### DATA LOCATION ####################
'data_file': [{"train_file": 'data/460-464-466_201710_30_neg_-1_train_0.csv', "test_file": 'data/460-464-466_201710_30_neg_-1_test_0.csv'}]
#################### MODEL LOCATION ####################
'model_type': ["RCNN"]
'model_name': ["RCNN-resnet-50"]
'base_model_path': ["models/templates/RCNN-resnet-50_5_layer_pretrained.pt"]
'output_dir': ["models/trained"]
#################### TASK ####################
'task_name': ["seedlings_first_untrained"]
'task_description': ["A second run of the negative sampling tests because the models were not saved from the first run."]
#################### TRAINING ####################
'optimiser': ['SGD']
'learning_rate': [2.0e-3]
'momentum': [0.9]
'weight_decay': [1.0e-4]
'epochs': [20]
'patience': [300]
'valid_ratio': [0.1]
'dataloader_num_workers': [5]
'train_batch_size': [5]
'eval_batch_size': [5]
'max_seq_length': [512]
'logging_steps': [2]
'seed': [1337]
'num_weights_tracked': [10]
'device': ["cuda:1"]
'develop': [False]
'clip': [1]
# For the moment can choose from [0.1, 0.25, 0.5, 0.75, 1, 2, 5, "all"]
'test_neg_ratio': [0.1, 0.25, 0.5, 0.75, 1, 2, 5, "all"]
'train_neg_ratio': [0.1, 0.25, 0.5, 0.75, 1, 2, 5, "all"]