# Is it possible to have hierarchical config files? XML? Hydra?
#################### DATA LOCATION ####################
'train_file': ['data/460-464-466_201710_30_train_0.csv', 'data/train_0.csv']
'test_file': ['data/460-464-466_201710_30_test_0.csv', "test_0.csv"]
#################### MODEL LOCATION ####################
'model_type': ["RCNN"]
'model_name': ["RCNN-resnet-50"]
'base_model_path': ["models/templates/RCNN-resnet-50_5_layer_pretrained.pt"]
'output_dir': ["models/trained"]
#################### TASK ####################
'task_name': ["seedlings_extra_data_vanilla_2"]
'task_description': ["A test to see how the network performs with the extra data. With new data as test set as well as old data. This time we draw the 464 samples from the combined split - that way there is no leakage"]
# Could include optimizer hyperparams by making this nested. Maybe different config files for optimiser here?
#################### TRAINING ####################
'optimiser': ['SGD']
'learning_rate': [2.0e-3]
'momentum': [0.9]
'weight_decay': [1.0e-4]
'epochs': [35]
'patience': [50]
'valid_ratio': [0.1]
'dataloader_num_workers': [5]
'train_batch_size': [5]
'eval_batch_size': [5]
'max_seq_length': [512]
'logging_steps': [2]
'seed': [1337]
'num_weights_tracked': [10]
'device': ["cuda:0"]
'develop': [False]
'clip': [1]