# Is it possible to have hierarchical config files? XML? Hydra?
#################### DATA LOCATION ####################
'train_file': ['data/site_464_201710_30_train.csv']
'test_file': ['data/site_464_201710_30_test.csv']
#################### MODEL LOCATION ####################
'model_type': ["RCNN"]
'model_name': ["RCNN-resnet-50"]
'base_model_path': ["models/templates/RCNN-resnet-50_5_layer_pretrained.pt"]
'output_dir': ["models/trained"]
#################### TASK ####################
'task_name': ["seedlings_clipping_3"]
'task_description': ["Quick test for different gradient clipping values on the progress over the first few epochs"]
# Could include optimizer hyperparams by making this nested. Maybe different config files for optimiser here?
#################### TRAINING ####################
'optimiser': ['SGD']
'learning_rate': [2.0e-1, 2.0e-3]
'momentum': [0.9]
'weight_decay': [1.0e-4]
'epochs': [10]
'patience': [50]
'valid_ratio': [0.1]
'dataloader_num_workers': [5]
'train_batch_size': [5]
'eval_batch_size': [5]
'max_seq_length': [512]
'logging_steps': [2]
'seed': [1337, 42]
'num_weights_tracked': [10]
'device': ["cuda:1"]
'develop': [False]
'clip': [5, 1, 0.5, 0.1, 0.025]